CREATE TABLE `rm_ttv_balance_cairan` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` date NOT NULL,
  `jam` time NOT NULL,
  `nadi` varchar(5) DEFAULT NULL,
  `respirasi` varchar(5) DEFAULT NULL,
  `suhu` varchar(5) DEFAULT NULL,
  `tensi` varchar(8) DEFAULT NULL,
  `bb` varchar(5) DEFAULT NULL,
  `tb` varchar(5) DEFAULT NULL,
  `diet` varchar(50) DEFAULT NULL,
  `kode_infus` varchar(50) DEFAULT NULL,
  `intake_makan` varchar(10) DEFAULT NULL,
  `intake_minum` varchar(10) DEFAULT NULL,
  `intake_ngt` varchar(10) DEFAULT NULL,
  `intake_transfusi` varchar(10) DEFAULT NULL,
  `intake_infus` varchar(10) DEFAULT NULL,
  `intake_sisa_infus` varchar(10) DEFAULT NULL,
  `jumlah_input` varchar(10) DEFAULT NULL,
  `output_urine` varchar(10) DEFAULT NULL,
  `output_muntah` varchar(10) DEFAULT NULL,
  `output_ngt` varchar(10) DEFAULT NULL,
  `output_iwl` varchar(10) DEFAULT NULL,
  `output_drain` varchar(10) DEFAULT NULL,
  `jumlah_output` varchar(10) DEFAULT NULL,
  `balance` varchar(10) DEFAULT NULL,
  `nik` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`no_rawat`,`tanggal`,`jam`),
  KEY `nik` (`nik`),
  CONSTRAINT `rm_ttv_balance_cairan_ibfk_1` FOREIGN KEY (`no_rawat`) REFERENCES `reg_periksa` (`no_rawat`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `rm_ttv_balance_cairan_ibfk_2` FOREIGN KEY (`nik`) REFERENCES `petugas` (`nip`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
