package rekammedis;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.CombinedDomainCategoryPlot;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

public class GrafikBalanceCairanRanap extends javax.swing.JDialog {
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2;
    private ResultSet rs,rs2;
    private int i=0;
    private String noRawat="";
    
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public GrafikBalanceCairanRanap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setSize(1285,674);
        
        HTMLEditorKit kit = new HTMLEditorKit();
//        LoadHTML.setEditable(true);
//        LoadHTML.setEditorKit(kit);
//        LoadHTML.setEditable(true);
//        LoadHTML.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
//        LoadHTML.setDocument(doc);
//        LoadHTML.setDocument(doc);
    ChkInput.setSelected(false);
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        PanelInput = new javax.swing.JPanel();
        TabRawat = new javax.swing.JTabbedPane();
        internalFrame9 = new widget.InternalFrame();
        Tensi1 = new widget.ScrollPane();
        jPanelSkalaNyeri = new javax.swing.JPanel();
        ChkInput = new widget.CekBox();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        BtnKeluar = new widget.Button();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Grafik Observasi TTV ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        PanelInput.setName("PanelInput"); // NOI18N
        PanelInput.setOpaque(false);
        PanelInput.setPreferredSize(new java.awt.Dimension(192, 330));
        PanelInput.setLayout(new java.awt.BorderLayout(1, 1));

        TabRawat.setBackground(new java.awt.Color(254, 255, 254));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setName("TabRawat"); // NOI18N

        internalFrame9.setBorder(null);
        internalFrame9.setName("internalFrame9"); // NOI18N
        internalFrame9.setLayout(new java.awt.BorderLayout(1, 1));

        Tensi1.setName("Tensi1"); // NOI18N
        Tensi1.setOpaque(true);

        jPanelSkalaNyeri.setName("jPanelSkalaNyeri"); // NOI18N
        Tensi1.setViewportView(jPanelSkalaNyeri);

        internalFrame9.add(Tensi1, java.awt.BorderLayout.CENTER);

        TabRawat.addTab("Grafik TTV", internalFrame9);

        PanelInput.add(TabRawat, java.awt.BorderLayout.CENTER);

        ChkInput.setMnemonic('I');
        ChkInput.setToolTipText("Alt+I");
        ChkInput.setBorderPainted(true);
        ChkInput.setBorderPaintedFlat(true);
        ChkInput.setEnabled(false);
        ChkInput.setFocusable(false);
        ChkInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChkInput.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChkInput.setName("ChkInput"); // NOI18N
        ChkInput.setPreferredSize(new java.awt.Dimension(193, 20));
        ChkInput.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkInput.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/145.png"))); // NOI18N
        ChkInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkInputActionPerformed(evt);
            }
        });
        PanelInput.add(ChkInput, java.awt.BorderLayout.PAGE_END);

        internalFrame1.add(PanelInput, java.awt.BorderLayout.PAGE_START);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(20, 30));
        panelisi1.add(label9);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void ChkInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkInputActionPerformed
        isForm();
    }//GEN-LAST:event_ChkInputActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnKeluar,BtnKeluar);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            GrafikBalanceCairanRanap dialog = new GrafikBalanceCairanRanap(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.CekBox ChkInput;
    private widget.TextBox Kd2;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JTabbedPane TabRawat;
    private widget.ScrollPane Tensi1;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame9;
    private javax.swing.JPanel jPanelSkalaNyeri;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    
    
    public void isCek(){

    }
    
    public void setNoRawat(String x,String y)
    {
        this.noRawat=x;

        ChkInput.setSelected(false);
        isForm();

        jPanelSkalaNyeri.removeAll();
        jPanelSkalaNyeri.setLayout(new java.awt.BorderLayout());
        JPanel chartPanelBc = createPanelBc(x);
        jPanelSkalaNyeri.add(chartPanelBc, java.awt.BorderLayout.CENTER);
        jPanelSkalaNyeri.validate();
        jPanelSkalaNyeri.repaint();
    }

    public void tampil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    public static JPanel createPanelBc(String noRawat) {
        JFreeChart chart = createChartBc(noRawat);
        ChartPanel panel = new ChartPanel(chart);
        return panel;
    }


    public static JFreeChart createChartBcCustom(java.util.List<String[]> pageData) {
        org.jfree.data.category.DefaultCategoryDataset datasetNadi = new org.jfree.data.category.DefaultCategoryDataset();
        org.jfree.data.category.DefaultCategoryDataset datasetResp = new org.jfree.data.category.DefaultCategoryDataset();
        org.jfree.data.category.DefaultCategoryDataset datasetSuhu = new org.jfree.data.category.DefaultCategoryDataset();
        
        for (int i=0; i<12; i++) {
            String[] arr = pageData.get(i);
            String period = String.valueOf(i+1); // Dummy unique category
            
            // Nadi (index 22)
            if (arr[22] != null && !arr[22].isEmpty() && !arr[22].equals("-")) {
                try { datasetNadi.addValue(Double.parseDouble(arr[22]), "Nadi", period); } catch(Exception e) {}
            } else { datasetNadi.addValue(null, "Nadi", period); }
            
            // Respirasi (index 23)
            if (arr[23] != null && !arr[23].isEmpty() && !arr[23].equals("-")) {
                try { datasetResp.addValue(Double.parseDouble(arr[23]), "Respirasi", period); } catch(Exception e) {}
            } else { datasetResp.addValue(null, "Respirasi", period); }
            
            // Suhu (index 24)
            if (arr[24] != null && !arr[24].isEmpty() && !arr[24].equals("-")) {
                try { datasetSuhu.addValue(Double.parseDouble(arr[24]), "Suhu", period); } catch(Exception e) {}
            } else { datasetSuhu.addValue(null, "Suhu", period); }
        }

        org.jfree.chart.labels.CategoryItemLabelGenerator timeLabelGenerator = new org.jfree.chart.labels.StandardCategoryItemLabelGenerator() {
            @Override
            public String generateLabel(org.jfree.data.category.CategoryDataset ds, int row, int col) {
                // Return time from pageData
                int idx = Integer.parseInt(ds.getColumnKey(col).toString()) - 1;
                String[] arr = pageData.get(idx);
                if (arr[1] != null && arr[1].length() >= 5) {
                    return arr[1].substring(0, 5); // HH:mm
                }
                return "";
            }
        };

        org.jfree.chart.axis.NumberAxis axisNadi = new org.jfree.chart.axis.NumberAxis("Nadi");
        axisNadi.setRange(30.0, 170.0);
        axisNadi.setTickLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 8));
        axisNadi.setLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 9));
        org.jfree.chart.renderer.category.LineAndShapeRenderer rendererNadi = new org.jfree.chart.renderer.category.LineAndShapeRenderer(true, true);
        rendererNadi.setSeriesPaint(0, java.awt.Color.RED);
        rendererNadi.setBaseItemLabelsVisible(true);
        rendererNadi.setBaseItemLabelGenerator(timeLabelGenerator);
        rendererNadi.setBaseItemLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 8));

        org.jfree.chart.plot.CategoryPlot subplot = new org.jfree.chart.plot.CategoryPlot();
        subplot.setDomainGridlinesVisible(true);
        subplot.setRangeGridlinesVisible(true);
        subplot.setRangeGridlinePaint(java.awt.Color.LIGHT_GRAY);
        subplot.setDomainGridlinePaint(java.awt.Color.LIGHT_GRAY);
        subplot.setBackgroundPaint(java.awt.Color.WHITE); // Make plot white

        subplot.setDataset(0, datasetNadi);
        subplot.setRangeAxis(0, axisNadi);
        subplot.setRenderer(0, rendererNadi);
        subplot.mapDatasetToRangeAxis(0, 0);

        org.jfree.chart.axis.NumberAxis axisResp = new org.jfree.chart.axis.NumberAxis("Resp");
        axisResp.setRange(-5.0, 65.0);
        axisResp.setTickLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 8));
        axisResp.setLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 9));
        org.jfree.chart.renderer.category.LineAndShapeRenderer rendererResp = new org.jfree.chart.renderer.category.LineAndShapeRenderer(true, true);
        rendererResp.setSeriesPaint(0, java.awt.Color.BLACK);
        rendererResp.setBaseItemLabelsVisible(true);
        rendererResp.setBaseItemLabelGenerator(timeLabelGenerator);
        rendererResp.setBaseItemLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 8));

        subplot.setDataset(1, datasetResp);
        subplot.setRangeAxis(1, axisResp);
        subplot.setRenderer(1, rendererResp);
        subplot.mapDatasetToRangeAxis(1, 1);

        org.jfree.chart.axis.NumberAxis axisSuhu = new org.jfree.chart.axis.NumberAxis("Suhu");
        axisSuhu.setRange(34.5, 41.5);
        axisSuhu.setTickLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 8));
        axisSuhu.setLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 9));
        org.jfree.chart.renderer.category.LineAndShapeRenderer rendererSuhu = new org.jfree.chart.renderer.category.LineAndShapeRenderer(true, true);
        rendererSuhu.setSeriesPaint(0, java.awt.Color.BLUE);
        rendererSuhu.setBaseItemLabelsVisible(true);
        rendererSuhu.setBaseItemLabelGenerator(timeLabelGenerator);
        rendererSuhu.setBaseItemLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 8));

        subplot.setDataset(2, datasetSuhu);
        subplot.setRangeAxis(2, axisSuhu);
        subplot.setRenderer(2, rendererSuhu);
        subplot.mapDatasetToRangeAxis(2, 2);

        subplot.setRangeAxisLocation(0, org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT);
        subplot.setRangeAxisLocation(1, org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT);
        subplot.setRangeAxisLocation(2, org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT);

        org.jfree.chart.axis.CategoryAxis domainAxis = new org.jfree.chart.axis.CategoryAxis("");
        domainAxis.setTickLabelsVisible(false); // Hide X-axis labels
        domainAxis.setTickMarksVisible(false); // Hide X-axis ticks
        // Make the category margins such that the points align with table columns
        domainAxis.setLowerMargin(0.04); 
        domainAxis.setUpperMargin(0.04);

        org.jfree.chart.plot.CombinedDomainCategoryPlot plot = new org.jfree.chart.plot.CombinedDomainCategoryPlot(domainAxis);
        plot.add(subplot, 1);
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setGap(0); // Remove gap

        JFreeChart result = new JFreeChart(
                null, // Remove Title
                new java.awt.Font("Tahoma", java.awt.Font.BOLD, 12),
                plot,
                true // Legend on
        );
        result.setBackgroundPaint(java.awt.Color.WHITE);
        
        // Put legend at the top so it doesn't take bottom space
        org.jfree.chart.title.LegendTitle legend = result.getLegend();
        legend.setPosition(org.jfree.ui.RectangleEdge.TOP);
        legend.setBackgroundPaint(java.awt.Color.WHITE);

        return result;
    }

    public static JFreeChart createChartBc(String noRawat) {
        org.jfree.chart.labels.CategoryItemLabelGenerator timeLabelGenerator = new org.jfree.chart.labels.StandardCategoryItemLabelGenerator() {
            @Override
            public String generateLabel(CategoryDataset ds, int row, int col) {
                String timeStr = ds.getColumnKey(col).toString();
                if(timeStr.length() > 10) {
                    return timeStr.substring(11, 16); // Only show HH:mm instead of HH:mm:ss to save space
                }
                return timeStr;
            }
        };

        // Nadi Dataset
        CategoryDataset datasetNadi = createDataset(noRawat, "nadi", "Nadi");
        NumberAxis axisNadi = new NumberAxis("Nadi");
        axisNadi.setRange(30.0, 170.0);
        LineAndShapeRenderer rendererNadi = new LineAndShapeRenderer(true, true);
        rendererNadi.setSeriesPaint(0, java.awt.Color.RED);
        rendererNadi.setBaseToolTipGenerator(new StandardCategoryToolTipGenerator());
        rendererNadi.setBaseItemLabelsVisible(true);
        rendererNadi.setBaseItemLabelGenerator(timeLabelGenerator);
        rendererNadi.setBaseItemLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 9));

        CategoryPlot subplot = new CategoryPlot();
        subplot.setDomainGridlinesVisible(true);
        
        subplot.setDataset(0, datasetNadi);
        subplot.setRangeAxis(0, axisNadi);
        subplot.setRenderer(0, rendererNadi);
        subplot.mapDatasetToRangeAxis(0, 0);

        // Respirasi Dataset
        CategoryDataset datasetResp = createDataset(noRawat, "respirasi", "Respirasi");
        NumberAxis axisResp = new NumberAxis("Respirasi");
        axisResp.setRange(-5.0, 65.0);
        LineAndShapeRenderer rendererResp = new LineAndShapeRenderer(true, true);
        rendererResp.setSeriesPaint(0, java.awt.Color.BLACK);
        rendererResp.setBaseToolTipGenerator(new StandardCategoryToolTipGenerator());
        rendererResp.setBaseItemLabelsVisible(true);
        rendererResp.setBaseItemLabelGenerator(timeLabelGenerator);
        rendererResp.setBaseItemLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 9));
        
        subplot.setDataset(1, datasetResp);
        subplot.setRangeAxis(1, axisResp);
        subplot.setRenderer(1, rendererResp);
        subplot.mapDatasetToRangeAxis(1, 1);

        // Suhu Dataset
        CategoryDataset datasetSuhu = createDataset(noRawat, "suhu", "Suhu");
        NumberAxis axisSuhu = new NumberAxis("Suhu");
        axisSuhu.setRange(34.5, 41.5);
        LineAndShapeRenderer rendererSuhu = new LineAndShapeRenderer(true, true);
        rendererSuhu.setSeriesPaint(0, java.awt.Color.BLUE);
        rendererSuhu.setBaseToolTipGenerator(new StandardCategoryToolTipGenerator());
        rendererSuhu.setBaseItemLabelsVisible(true);
        rendererSuhu.setBaseItemLabelGenerator(timeLabelGenerator);
        rendererSuhu.setBaseItemLabelFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 9));
        
        subplot.setDataset(2, datasetSuhu);
        subplot.setRangeAxis(2, axisSuhu);
        subplot.setRenderer(2, rendererSuhu);
        subplot.mapDatasetToRangeAxis(2, 2);

        // Put all axes on the left
        subplot.setRangeAxisLocation(0, org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT);
        subplot.setRangeAxisLocation(1, org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT);
        subplot.setRangeAxisLocation(2, org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT);
        
        CategoryAxis domainAxis = new CategoryAxis("");
        CombinedDomainCategoryPlot plot = new CombinedDomainCategoryPlot(domainAxis);
        plot.add(subplot, 1);
        CategoryAxis domainAxis2 = plot.getDomainAxis();
        domainAxis2.setCategoryLabelPositions(CategoryLabelPositions.DOWN_90);
        
        JFreeChart result = new JFreeChart(
                "Grafik Observasi TTV (Nadi, Respirasi, Suhu)",
                new Font("SansSerif", Font.PLAIN, 12), plot, true);
        return result;
    }

    public static CategoryDataset createDataset(String noRawat, String field, String seriesName) {
        DefaultCategoryDataset result = new DefaultCategoryDataset();
        try {
            Statement stat = koneksiDB.condb().createStatement();
            ResultSet rs = stat.executeQuery("select concat(tanggal,' ',jam) as period, " + field + " as nilai " +
               "from rm_ttv_balance_cairan where no_rawat='"+noRawat+"' order by tanggal, jam");
            while (rs.next()) {
                String tksbr = rs.getString("period");
                String valStr = rs.getString("nilai");
                double val = 0;
                try {
                    val = Double.parseDouble(valStr);
                } catch(Exception e) {
                    val = 0;
                }
                if (val > 0) {
                    result.addValue(val, seriesName, tksbr);
                }
            }
        } catch (SQLException e) {
            System.out.println("Notifikasi Q: " + e);
        }
        return result;
    }

      private void isForm(){
        if(ChkInput.isSelected()==true){
            ChkInput.setVisible(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH,645)); 
            
            ChkInput.setVisible(true);
        }else if(ChkInput.isSelected()==false){           
            ChkInput.setVisible(false);            
            PanelInput.setPreferredSize(new Dimension(WIDTH,645)); 
            
            ChkInput.setVisible(true);
        }
    }
}
